Repository prjemian/punx, pull requests merged in 2021-11, with the labels that each got.

#148 require minimum h5py version (v3+)
  .github/workflows/unit-tests-pytest.yml
  environment.yml
  punx/tests/test_issue133.py
Labels: task

#147 do not error for missing external file links
  punx/data/DLS_i03_i04_NXmx_Therm_6_2.nxs
  punx/h5tree.py
  punx/tests/test_issue130.py
  punx/tests/test_issue131.py
Labels: bug

#151 NEW: Check additional places for GitHub credentials
  punx/github_handler.py
Labels: enhancement

#150 render external link info, even when external file is missing
  punx/h5tree.py
  punx/tests/test_issue130.py
  punx/tests/test_issue18.py
  punx/utils.py
Labels: task

#157 bugfix: revise search algorithm for GitHub token
  punx/github_handler.py
  punx/tests/test_github_handler.py
Labels: task

#154 DOC: Remove Depsy badge from GitHub README
  README.rst
Labels: task

#159 Fix some hints from LGTM
  punx/github_handler.py
  punx/validate.py
  punx/validations/item_name.py
  setup.py
Labels: task

#155 API: Render axes attributes as list of double quoted strings
  .github/workflows/unit-tests-pytest.yml
  punx/h5tree.py
  punx/tests/test_data_files.py
  punx/tests/test_issue129.py
  punx/tests/test_issue130.py
  punx/tests/test_issue131.py
  punx/tests/test_issue18.py
  punx/tests/test_utils.py
  punx/utils.py
  punx/validate.py
  punx/validations/application_definition.py
Labels: task

#161 refactor README
  MANIFEST.in
  README.md
  README.rst
  punx/__init__.py
  setup.cfg
  setup.py
Labels: task
