Repository prjemian/punx, pull requests merged in 2022-07, with the labels that each got.

#203 directory is contributed_definitions
  punx/validations/application_definition.py
Labels: bug

#202 the value of an attribute is not always a string
  punx/validations/hdf5_group_items_in_base_class.py
Labels: bug

#209 refactor to use micromamba in CI
  .github/workflows/unit-tests-pytest.yml
  punx/nxdl_manager.py
Labels: enhancement, task, test

#207 support various compression formats used by EPICS area detector
  environment.yml
  punx/tests/test_issue133.py
  punx/utils.py
  punx/validate.py
Labels: enhancement
